# filepath: src/services/regions.py

"""Region taxonomy: explicit region -> country-name lists (concept 5).

Country names are lowercase English, matching the canonical values the
verification component writes into verification_data.location_country.
This file IS the definition — edit it to change what a region means.
"""

EUROPE = [
    "albania",
    "andorra",
    "austria",
    "belarus",
    "belgium",
    "bosnia and herzegovina",
    "bulgaria",
    "croatia",
    "cyprus",
    "czechia",
    "denmark",
    "estonia",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "iceland",
    "ireland",
    "italy",
    "kosovo",
    "latvia",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "malta",
    "moldova",
    "monaco",
    "montenegro",
    "netherlands",
    "north macedonia",
    "norway",
    "poland",
    "portugal",
    "romania",
    "russia",
    "san marino",
    "serbia",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
    "switzerland",
    "ukraine",
    "united kingdom",
]

EU = [
    "austria",
    "belgium",
    "bulgaria",
    "croatia",
    "cyprus",
    "czechia",
    "denmark",
    "estonia",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "ireland",
    "italy",
    "latvia",
    "lithuania",
    "luxembourg",
    "malta",
    "netherlands",
    "poland",
    "portugal",
    "romania",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
]

MIDDLE_EAST = [
    "bahrain",
    "iran",
    "iraq",
    "israel",
    "jordan",
    "kuwait",
    "lebanon",
    "oman",
    "palestine",
    "qatar",
    "saudi arabia",
    "syria",
    "turkey",
    "united arab emirates",
    "yemen",
]

AFRICA = [
    "algeria",
    "angola",
    "benin",
    "botswana",
    "burkina faso",
    "burundi",
    "cameroon",
    "chad",
    "democratic republic of the congo",
    "egypt",
    "ethiopia",
    "gabon",
    "ghana",
    "guinea",
    "ivory coast",
    "kenya",
    "libya",
    "madagascar",
    "malawi",
    "mali",
    "mauritius",
    "morocco",
    "mozambique",
    "namibia",
    "niger",
    "nigeria",
    "rwanda",
    "senegal",
    "sierra leone",
    "somalia",
    "south africa",
    "south sudan",
    "sudan",
    "tanzania",
    "togo",
    "tunisia",
    "uganda",
    "zambia",
    "zimbabwe",
]

LATAM = [
    "argentina",
    "bolivia",
    "brazil",
    "chile",
    "colombia",
    "costa rica",
    "cuba",
    "dominican republic",
    "ecuador",
    "el salvador",
    "guatemala",
    "honduras",
    "mexico",
    "nicaragua",
    "panama",
    "paraguay",
    "peru",
    "uruguay",
    "venezuela",
]

APAC = [
    "australia",
    "bangladesh",
    "cambodia",
    "china",
    "hong kong",
    "india",
    "indonesia",
    "japan",
    "kazakhstan",
    "kyrgyzstan",
    "laos",
    "malaysia",
    "mongolia",
    "myanmar",
    "nepal",
    "new zealand",
    "pakistan",
    "philippines",
    "singapore",
    "south korea",
    "sri lanka",
    "taiwan",
    "thailand",
    "uzbekistan",
    "vietnam",
]

NORTH_AMERICA = ["canada", "united states"]

REGIONS: dict[str, list[str]] = {
    "emea": sorted(set(EUROPE + MIDDLE_EAST + AFRICA)),
    "europe": EUROPE,
    "eu": EU,
    "middle east": MIDDLE_EAST,
    "mena": sorted(set(MIDDLE_EAST + ["algeria", "egypt", "libya", "morocco", "tunisia"])),
    "africa": AFRICA,
    "latam": LATAM,
    "apac": APAC,
    "north america": NORTH_AMERICA,
    "dach": ["austria", "germany", "switzerland"],
    "nordics": ["denmark", "finland", "iceland", "norway", "sweden"],
    "benelux": ["belgium", "luxembourg", "netherlands"],
}


def resolve_region(name: str) -> list[str] | None:
    """Region name -> lowercase country list, or None if unknown."""
    key = " ".join(name.strip().lower().replace("_", " ").replace("-", " ").split())
    return REGIONS.get(key)
