"""phone verification: users phone columns and sms_verifications

Revision ID: 8231dda0eb4a
Revises: 752f056635b2
Create Date: 2026-06-12 09:31:45.680901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8231dda0eb4a'
down_revision: Union[str, Sequence[str], None] = '752f056635b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sms_verifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_verifications'))
    )
    with op.batch_alter_table('sms_verifications', schema=None) as batch_op:
        batch_op.create_index('ix_sms_verifications_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_verifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_column('phone_verified_at')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('sms_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_verifications_user_id'))
        batch_op.drop_index('ix_sms_verifications_user_created')

    op.drop_table('sms_verifications')
    # ### end Alembic commands ###
