"""initial schema

Revision ID: f9de73792c91
Revises: 
Create Date: 2026-06-12 07:52:42.351047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9de73792c91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_time', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_type_time', ['event_type', 'created_at'], unique=False)

    op.create_table('proof_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proof_name', sa.String(length=100), nullable=False),
    sa.Column('proof_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_requirements', sa.JSON(), nullable=False),
    sa.Column('extraction_capabilities', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_types')),
    sa.UniqueConstraint('proof_name', name=op.f('uq_proof_types_proof_name'))
    )
    with op.batch_alter_table('proof_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proof_types_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('telegram_handle', sa.String(length=64), nullable=True),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('verification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expires_after_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_types')),
    sa.UniqueConstraint('verification_name', name=op.f('uq_verification_types_verification_name'))
    )
    with op.batch_alter_table('verification_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_types_tier'), ['tier'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.Column('you_earn', sa.Float(), nullable=False),
    sa.Column('num_jumpers', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('accept_jumpers_manually', sa.Boolean(), nullable=False),
    sa.Column('launcher_review', sa.Boolean(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('operation_requirements', sa.JSON(), nullable=True),
    sa.Column('other_requirements', sa.JSON(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('partition_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tasks_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('user_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proof_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proof_type_id'], ['proof_types.id'], name=op.f('fk_user_proofs_proof_type_id_proof_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_proofs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_proofs'))
    )
    with op.batch_alter_table('user_proofs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_proofs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_proofs_user_id'), ['user_id'], unique=False)

    op.create_table('user_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verification_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_verifications_user_id_users')),
    sa.ForeignKeyConstraint(['verification_type_id'], ['verification_types.id'], name=op.f('fk_user_verifications_verification_type_id_verification_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_verifications'))
    )
    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_verifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('verification_proof_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_type_id', sa.Integer(), nullable=False),
    sa.Column('proof_type_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('alternative_group', sa.Integer(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proof_type_id'], ['proof_types.id'], name=op.f('fk_verification_proof_requirements_proof_type_id_proof_types')),
    sa.ForeignKeyConstraint(['verification_type_id'], ['verification_types.id'], name=op.f('fk_verification_proof_requirements_verification_type_id_verification_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_proof_requirements'))
    )
    with op.batch_alter_table('verification_proof_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_proof_requirements_id'), ['id'], unique=False)

    op.create_table('jumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('jumper_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jumper_id'], ['users.id'], name=op.f('fk_jumps_jumper_id_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_jumps_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jumps')),
    sa.UniqueConstraint('task_id', 'jumper_id', name=op.f('uq_jumps_task_id'))
    )
    with op.batch_alter_table('jumps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jumps_jumper_id'), ['jumper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jumps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jumps_task_id'), ['task_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('coin_ticker', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tx_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_payments_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('verification_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('verification_source_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_data_user_id_users')),
    sa.ForeignKeyConstraint(['verification_source_id'], ['user_verifications.id'], name=op.f('fk_verification_data_verification_source_id_user_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_data'))
    )
    with op.batch_alter_table('verification_data', schema=None) as batch_op:
        batch_op.create_index('idx_field_search', ['field_name', 'field_value'], unique=False)
        batch_op.create_index('idx_user_current_data', ['user_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_data_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_data_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_data_user_id'), ['user_id'], unique=False)

    op.create_table('verification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_verification_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_verification_id'], ['user_verifications.id'], name=op.f('fk_verification_history_user_verification_id_user_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_history'))
    )
    with op.batch_alter_table('verification_history', schema=None) as batch_op:
        batch_op.create_index('idx_verification_history_chronological', ['user_verification_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_history_user_verification_id'), ['user_verification_id'], unique=False)

    op.create_table('verification_proof_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_verification_id', sa.Integer(), nullable=False),
    sa.Column('user_proof_id', sa.Integer(), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_proof_id'], ['user_proofs.id'], name=op.f('fk_verification_proof_usage_user_proof_id_user_proofs')),
    sa.ForeignKeyConstraint(['user_verification_id'], ['user_verifications.id'], name=op.f('fk_verification_proof_usage_user_verification_id_user_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_proof_usage'))
    )
    with op.batch_alter_table('verification_proof_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_proof_usage_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_proof_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_proof_usage_id'))

    op.drop_table('verification_proof_usage')
    with op.batch_alter_table('verification_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_history_user_verification_id'))
        batch_op.drop_index(batch_op.f('ix_verification_history_id'))
        batch_op.drop_index(batch_op.f('ix_verification_history_created_at'))
        batch_op.drop_index('idx_verification_history_chronological')

    op.drop_table('verification_history')
    with op.batch_alter_table('verification_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_data_is_current'))
        batch_op.drop_index(batch_op.f('ix_verification_data_id'))
        batch_op.drop_index(batch_op.f('ix_verification_data_field_name'))
        batch_op.drop_index('idx_user_current_data')
        batch_op.drop_index('idx_field_search')

    op.drop_table('verification_data')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_task_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))

    op.drop_table('payments')
    with op.batch_alter_table('jumps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jumps_task_id'))
        batch_op.drop_index(batch_op.f('ix_jumps_status'))
        batch_op.drop_index(batch_op.f('ix_jumps_jumper_id'))

    op.drop_table('jumps')
    with op.batch_alter_table('verification_proof_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_proof_requirements_id'))

    op.drop_table('verification_proof_requirements')
    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_verifications_id'))

    op.drop_table('user_verifications')
    with op.batch_alter_table('user_proofs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_proofs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_proofs_id'))

    op.drop_table('user_proofs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_category'))

    op.drop_table('tasks')
    with op.batch_alter_table('verification_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_types_tier'))
        batch_op.drop_index(batch_op.f('ix_verification_types_id'))

    op.drop_table('verification_types')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('proof_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proof_types_id'))

    op.drop_table('proof_types')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_type_time')
        batch_op.drop_index('ix_audit_actor_time')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
